name: "SharePoint Online Copy"
description: "Creates a zip file of the current repository and copies it to a given SharePoint Online directory."
author: "John Fabry"
branding:
  color: "purple"
inputs:
  tenant_id:
    description: "Office 365 tenant"
    required: true
  aad_endpoint:
    description: "URL to target as the Azure AD endpoint."
    required: true
    default: "https://login.microsoftonline.com"
  graph_endpoint:
    description: "URL to target as the Graph API endpoint."
    required: true
    default: "https://graph.microsoft.com"
  spo_path:
    description: "API path and site collection ID."
    required: true
  client_id:
    description: "O365 Graph API client ID"
    required: true
  client_secret:
    description: "O365 Graph API client secret"
    required: true
  base_name:
    description: "Prefix for the archive file"
    required: true
    default: ${{ github.event.repository.name }}
  archive_count:
    description: "Number of archives to keep in SharePoint."
    required: true
    default: "4"
  directory_path:
    description: "Path to archive."
    required: true
    default: ${{ github.workspace }}
  logging:
    description: "Log level to output. Must be one of DEBUG, INFO, WARNING, or ERROR."
    required: true
    default: "INFO"
runs:
  using: "node20"
  main: "./dist/index.js"
